// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: pb/wasabee.proto

package federation

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommunityID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Googleid      string `protobuf:"bytes,1,opt,name=googleid,proto3" json:"googleid,omitempty"`
	Communityname string `protobuf:"bytes,2,opt,name=communityname,proto3" json:"communityname,omitempty"`
}

func (x *CommunityID) Reset() {
	*x = CommunityID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_wasabee_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommunityID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommunityID) ProtoMessage() {}

func (x *CommunityID) ProtoReflect() protoreflect.Message {
	mi := &file_pb_wasabee_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommunityID.ProtoReflect.Descriptor instead.
func (*CommunityID) Descriptor() ([]byte, []int) {
	return file_pb_wasabee_proto_rawDescGZIP(), []int{0}
}

func (x *CommunityID) GetGoogleid() string {
	if x != nil {
		return x.Googleid
	}
	return ""
}

func (x *CommunityID) GetCommunityname() string {
	if x != nil {
		return x.Communityname
	}
	return ""
}

type AgentLocation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Googleid string  `protobuf:"bytes,1,opt,name=googleid,proto3" json:"googleid,omitempty"`
	Lat      float32 `protobuf:"fixed32,2,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng      float32 `protobuf:"fixed32,3,opt,name=lng,proto3" json:"lng,omitempty"`
}

func (x *AgentLocation) Reset() {
	*x = AgentLocation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_wasabee_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentLocation) ProtoMessage() {}

func (x *AgentLocation) ProtoReflect() protoreflect.Message {
	mi := &file_pb_wasabee_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentLocation.ProtoReflect.Descriptor instead.
func (*AgentLocation) Descriptor() ([]byte, []int) {
	return file_pb_wasabee_proto_rawDescGZIP(), []int{1}
}

func (x *AgentLocation) GetGoogleid() string {
	if x != nil {
		return x.Googleid
	}
	return ""
}

func (x *AgentLocation) GetLat() float32 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *AgentLocation) GetLng() float32 {
	if x != nil {
		return x.Lng
	}
	return 0
}

type IntelData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Googleid string `protobuf:"bytes,1,opt,name=googleid,proto3" json:"googleid,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Faction  string `protobuf:"bytes,3,opt,name=faction,proto3" json:"faction,omitempty"`
}

func (x *IntelData) Reset() {
	*x = IntelData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_wasabee_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IntelData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntelData) ProtoMessage() {}

func (x *IntelData) ProtoReflect() protoreflect.Message {
	mi := &file_pb_wasabee_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntelData.ProtoReflect.Descriptor instead.
func (*IntelData) Descriptor() ([]byte, []int) {
	return file_pb_wasabee_proto_rawDescGZIP(), []int{2}
}

func (x *IntelData) GetGoogleid() string {
	if x != nil {
		return x.Googleid
	}
	return ""
}

func (x *IntelData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *IntelData) GetFaction() string {
	if x != nil {
		return x.Faction
	}
	return ""
}

type FBData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Googleid string `protobuf:"bytes,1,opt,name=googleid,proto3" json:"googleid,omitempty"`
	Token    string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *FBData) Reset() {
	*x = FBData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_wasabee_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FBData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FBData) ProtoMessage() {}

func (x *FBData) ProtoReflect() protoreflect.Message {
	mi := &file_pb_wasabee_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FBData.ProtoReflect.Descriptor instead.
func (*FBData) Descriptor() ([]byte, []int) {
	return file_pb_wasabee_proto_rawDescGZIP(), []int{3}
}

func (x *FBData) GetGoogleid() string {
	if x != nil {
		return x.Googleid
	}
	return ""
}

func (x *FBData) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type Token struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tokenid string `protobuf:"bytes,1,opt,name=tokenid,proto3" json:"tokenid,omitempty"`
}

func (x *Token) Reset() {
	*x = Token{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_wasabee_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token) ProtoMessage() {}

func (x *Token) ProtoReflect() protoreflect.Message {
	mi := &file_pb_wasabee_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token.ProtoReflect.Descriptor instead.
func (*Token) Descriptor() ([]byte, []int) {
	return file_pb_wasabee_proto_rawDescGZIP(), []int{4}
}

func (x *Token) GetTokenid() string {
	if x != nil {
		return x.Tokenid
	}
	return ""
}

type Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Error) Reset() {
	*x = Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_wasabee_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_pb_wasabee_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_pb_wasabee_proto_rawDescGZIP(), []int{5}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pb_wasabee_proto protoreflect.FileDescriptor

var file_pb_wasabee_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x62, 0x2f, 0x77, 0x61, 0x73, 0x61, 0x62, 0x65, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x07, 0x77, 0x61, 0x73, 0x61, 0x62, 0x65, 0x65, 0x22, 0x4f, 0x0a, 0x0b, 0x43,
	0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x69, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e,
	0x69, 0x74, 0x79, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63,
	0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x4f, 0x0a, 0x0d,
	0x41, 0x67, 0x65, 0x6e, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a,
	0x08, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x61, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x6c, 0x61, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6c,
	0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x6c, 0x6e, 0x67, 0x22, 0x55, 0x0a,
	0x09, 0x49, 0x6e, 0x74, 0x65, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x66, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0x3a, 0x0a, 0x06, 0x46, 0x42, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1a,
	0x0a, 0x08, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x22, 0x21, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x69, 0x64, 0x22, 0x35, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0xa7, 0x02, 0x0a, 0x11, 0x57,
	0x61, 0x73, 0x61, 0x62, 0x65, 0x65, 0x46, 0x65, 0x64, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x38, 0x0a, 0x0e, 0x53, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79,
	0x49, 0x44, 0x12, 0x14, 0x2e, 0x77, 0x61, 0x73, 0x61, 0x62, 0x65, 0x65, 0x2e, 0x43, 0x6f, 0x6d,
	0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x49, 0x44, 0x1a, 0x0e, 0x2e, 0x77, 0x61, 0x73, 0x61, 0x62,
	0x65, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x00, 0x12, 0x3c, 0x0a, 0x10, 0x53, 0x65,
	0x74, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16,
	0x2e, 0x77, 0x61, 0x73, 0x61, 0x62, 0x65, 0x65, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x4c, 0x6f,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x0e, 0x2e, 0x77, 0x61, 0x73, 0x61, 0x62, 0x65, 0x65,
	0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x00, 0x12, 0x34, 0x0a, 0x0c, 0x53, 0x65, 0x74, 0x49,
	0x6e, 0x74, 0x65, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x2e, 0x77, 0x61, 0x73, 0x61, 0x62,
	0x65, 0x65, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x1a, 0x0e, 0x2e, 0x77,
	0x61, 0x73, 0x61, 0x62, 0x65, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x00, 0x12, 0x35,
	0x0a, 0x10, 0x41, 0x64, 0x64, 0x46, 0x69, 0x72, 0x65, 0x62, 0x61, 0x73, 0x65, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x12, 0x0f, 0x2e, 0x77, 0x61, 0x73, 0x61, 0x62, 0x65, 0x65, 0x2e, 0x46, 0x42, 0x44,
	0x61, 0x74, 0x61, 0x1a, 0x0e, 0x2e, 0x77, 0x61, 0x73, 0x61, 0x62, 0x65, 0x65, 0x2e, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x22, 0x00, 0x12, 0x2d, 0x0a, 0x09, 0x52, 0x65, 0x76, 0x6f, 0x6b, 0x65, 0x4a,
	0x57, 0x54, 0x12, 0x0e, 0x2e, 0x77, 0x61, 0x73, 0x61, 0x62, 0x65, 0x65, 0x2e, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x1a, 0x0e, 0x2e, 0x77, 0x61, 0x73, 0x61, 0x62, 0x65, 0x65, 0x2e, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x22, 0x00, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x77, 0x61, 0x73, 0x61, 0x62, 0x65, 0x65, 0x2d, 0x70, 0x72, 0x6f, 0x6a, 0x65,
	0x63, 0x74, 0x2f, 0x57, 0x61, 0x73, 0x61, 0x62, 0x65, 0x65, 0x2d, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2f, 0x66, 0x65, 0x64, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_wasabee_proto_rawDescOnce sync.Once
	file_pb_wasabee_proto_rawDescData = file_pb_wasabee_proto_rawDesc
)

func file_pb_wasabee_proto_rawDescGZIP() []byte {
	file_pb_wasabee_proto_rawDescOnce.Do(func() {
		file_pb_wasabee_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_wasabee_proto_rawDescData)
	})
	return file_pb_wasabee_proto_rawDescData
}

var file_pb_wasabee_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pb_wasabee_proto_goTypes = []interface{}{
	(*CommunityID)(nil),   // 0: wasabee.CommunityID
	(*AgentLocation)(nil), // 1: wasabee.AgentLocation
	(*IntelData)(nil),     // 2: wasabee.IntelData
	(*FBData)(nil),        // 3: wasabee.FBData
	(*Token)(nil),         // 4: wasabee.Token
	(*Error)(nil),         // 5: wasabee.Error
}
var file_pb_wasabee_proto_depIdxs = []int32{
	0, // 0: wasabee.WasabeeFederation.SetCommunityID:input_type -> wasabee.CommunityID
	1, // 1: wasabee.WasabeeFederation.SetAgentLocation:input_type -> wasabee.AgentLocation
	2, // 2: wasabee.WasabeeFederation.SetIntelData:input_type -> wasabee.IntelData
	3, // 3: wasabee.WasabeeFederation.AddFirebaseToken:input_type -> wasabee.FBData
	4, // 4: wasabee.WasabeeFederation.RevokeJWT:input_type -> wasabee.Token
	5, // 5: wasabee.WasabeeFederation.SetCommunityID:output_type -> wasabee.Error
	5, // 6: wasabee.WasabeeFederation.SetAgentLocation:output_type -> wasabee.Error
	5, // 7: wasabee.WasabeeFederation.SetIntelData:output_type -> wasabee.Error
	5, // 8: wasabee.WasabeeFederation.AddFirebaseToken:output_type -> wasabee.Error
	5, // 9: wasabee.WasabeeFederation.RevokeJWT:output_type -> wasabee.Error
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_wasabee_proto_init() }
func file_pb_wasabee_proto_init() {
	if File_pb_wasabee_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_wasabee_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommunityID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_wasabee_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentLocation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_wasabee_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IntelData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_wasabee_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FBData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_wasabee_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Token); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_wasabee_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_wasabee_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_wasabee_proto_goTypes,
		DependencyIndexes: file_pb_wasabee_proto_depIdxs,
		MessageInfos:      file_pb_wasabee_proto_msgTypes,
	}.Build()
	File_pb_wasabee_proto = out.File
	file_pb_wasabee_proto_rawDesc = nil
	file_pb_wasabee_proto_goTypes = nil
	file_pb_wasabee_proto_depIdxs = nil
}
